<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // 创建Promise对象
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('Success!')
                // reject('Fatal!')
            }, 1000)
        })
        
         let result = p.then((value) => {   //then（）函数返回的实际也是一个Promise对象
            console.log(value)
            // 非 Promise 类型的属性
            /**
             * 1.当回调后，返回的是非Promise类型的属性时
             * 状态为fulfilled，then（）函数的返回值为对象的成功值
             * 如reutnr 'return value'，返回的Promise对象值为'return value'，如果没有返回值，是undefined
            */
            // return 'return value'
            /**
             * Promise {<pending>}
             * [[Prototype]]: Promise
             * [[PromiseState]]: "fulfilled"
             * [[PromiseResult]]: "return value"
            */

            // Promise 对象
            /**
             * 当回调后，返回的是Promise类型的对象时，then（）函数的返回值为这个Promise对象的状态值
            */

            // return new Promise((resolve, reject) => {
            //     // resolve('ok')
                // reject('Defeat')
                /**
                 * Promise {<pending>}
                 * [[Prototype]]: Promise
                 * [[PromiseState]]: "rejected"
                 * [[PromiseResult]]: "Defeat"
                */
            // })

            // 抛出错误
            /**
             * 当回调后，如果抛出的异常，则then（）函数的返回值状态也是rejected
            */
            throw new Error('出错啦!')
            /**
             * Promise {<pending>}
             * [[Prototype]]: Promise
             * [[PromiseState]]: "rejected"
             * [[PromiseResult]]: Error: 出错啦! at file........
            */
        }, (reason) => {
            console.error('reason')
        })
        console.log(result)
    </script>
</body>
</html>